version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: vvue-redis-container
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: vvue-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: vvue
