spring:
  profiles:
    default: prod

server:
  servlet:
    context-path: /back/api
  port:
    8080
swagger:
  url: https://api.vvue.site/back/api

cloud:
  aws:
    credentials:
      accessKey: ${AWS_IAM_ACCESSKEY}       # AWS IAM AccessKey 적기
      secretKey: ${AWS_IAM_SECRETKEY}   # AWS IAM SecretKey 적기
    s3:
      bucket: vvue-s3    # ex) marryting-gyunny
      prefix: https://cdn.vvue.site/
    region:
      static: us-east-1
    stack:
      auto: false
  gcp:
    firebase:
      service-account: classpath:firebase-service-account.json
auth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    scope:
      - email
      - profile
    token-req-url: https://oauth2.googleapis.com
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    scope:
      - profile_nickname
      - profile_image
      - account_email
    token-req-url: https://kauth.kakao.com/oauth/token
    user-info-request-url: https://kapi.kakao.com/v2/user/me
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"